version: "3"

services:

  reurl-db:
    image: mariadb
    container_name: ${APP}-db
    restart: unless-stopped
    environment:
      TZ: Asia/Taipei
      #- MARIADB_USER=user
      #- MARIADB_PASSWORD=password
      MARIADB_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${APP}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      default:
        ipv4_address: ${subnet}.0.2

  reurl-app:
    image: ${image}
    container_name: ${APP}-app
    restart: unless-stopped
    environment:
      TZ: Asia/Taipei
    volumes:
      - ../:/usr/share/nginx/html
      - ./nginx:/etc/nginx
      #- ./php:/etc/php
      - ./entrypoint.sh:/docker-entrypoint.d/custom.sh
    networks:
      default:
        ipv4_address: ${subnet}.0.3
      
networks:
  default:
    name: ${network}
    external: true

